### Engine ###

kick_speed: 7.2

# Distances and positions
engine_rate: 500
foot_rise: 0.11
foot_distance: 0.21
kick_windup_distance: 0.34
trunk_height: 0.41
trunk_roll: 0.101229096615671
trunk_pitch: -0.502654824574367
trunk_yaw: 0.301941960595019

# Timings
move_trunk_time: 0.28
raise_foot_time: 0.25
move_to_ball_time: 0.35
kick_time: 0.11
move_back_time: 0.25
lower_foot_time: 0.17
move_trunk_back_time: 0.11

# Decisions
choose_foot_corridor_width: 0.4

### Stabilizer ###
use_center_of_pressure: false
stabilizing_point_x: 0.01
stabilizing_point_y: -0.03

# these values are used only if use_center_of_pressure is true
pid_x/p: 0.2
pid_x/i: 0
pid_x/d: 0
pid_y/p: 0.5
pid_y/i: 0.0015
pid_y/d: 1.5

### Visualization ###
spline_smoothness: 100
