### Engine ###

# Distances and positions
engine_rate: 500


# Decisions
choose_foot_corridor_width: 0.4

### Stabilizer ###
use_center_of_pressure: false

ankle_time: 0.01
ball_x: 0.17
foot_distance: 0.2
foot_rise: 0.15
goal_x: 0.1
kick_speed: 5.59
kick_time: 0.05
kick_windup_distance: 0.57
knee_time: 0.15
lower_foot_time: 0.5
move_back_time: 0.22
move_to_ball_time: 0.22
move_trunk_back_time: 0.25
move_trunk_time: 1.0
raise_foot_time: 0.7
stabilizing_point_x: -0.025
stabilizing_point_y: 0.01
trunk_height: 0.42
trunk_pitch: 0
trunk_roll: 0.2
trunk_yaw: 0
windup_ankle: 30.0
windup_hip: 30.0
windup_knee: 120.0

# these values are used only if use_center_of_pressure is true
pid_x/p: 0.2
pid_x/i: 0
pid_x/d: 0
pid_y/p: 0.5
pid_y/i: 0.0015
pid_y/d: 1.5

### Visualization ###
spline_smoothness: 100
