### Engine ###

# Distances and positions
engine_rate: 500
foot_rise: 0.13
foot_distance: 0.18
kick_windup_distance: 0.2
trunk_height: 0.4
trunk_roll: 0.08
trunk_pitch: 0.0
trunk_yaw: -0.111

# Timings
move_trunk_time: 0.7
velocity: 1.4

# Decisions
choose_foot_corridor_width: 0.4

### Stabilizer ###
use_center_of_pressure: false
stabilizing_point_x: 0.019
stabilizing_point_y: -0.05

pid_x/p: 0.2
pid_x/i: 0
pid_x/d: 0
pid_y/p: 0.5
pid_y/i: 0.0015
pid_y/d: 1.5
pid_cartesian_hip_x/p: 1
pid_cartesian_hip_y/p: 1
pid_cartesian_trunk_x/p: 1
pid_cartesian_trunk_y/p: 1
pid_joint_hip_x/p: 1
pid_joint_hip_y/p: 1
pid_joint_ankle_imu_orientation_roll/p: 1
pid_joint_ankle_imu_orientation_pitch/p: 1
pid_joint_ankle_imu_velocity_roll/p: 1
pid_joint_ankle_imu_velocity_pitch/p: 1
pid_joint_hip_imu_velocity_roll/p: 1
pid_joint_hip_imu_velocity_pitch/p: 1

### Visualization ###
spline_smoothness: 100
