### Engine ###

foot_distance: 0.22
foot_rise: 0.11
kick_speed: 6.7
kick_time: 0.11
kick_windup_distance: 0.32
lower_foot_time: 0.01
move_back_time: 0.17
move_to_ball_time: 0.33
move_trunk_back_time: 0.11
move_trunk_time: 0.31
raise_foot_time: 0.21
stabilizing_point_x: 0.0
stabilizing_point_y: -0.03
trunk_height: 0.41
trunk_pitch: -0.469493568786475
trunk_roll: 0.0401425727958696
trunk_yaw: 0.239110107523223

# Distances and positions
engine_rate: 500

# Timings

# Decisions
choose_foot_corridor_width: 0.4

### Stabilizer ###
use_center_of_pressure: false

# these values are used only if use_center_of_pressure is true
pid_x/p: 0.2
pid_x/i: 0
pid_x/d: 0
pid_y/p: 0.5
pid_y/i: 0.0015
pid_y/d: 1.5

### Visualization ###
spline_smoothness: 100
