### Engine ###

# Distances and positions
engine_rate: 500
foot_rise: 0.1
foot_distance: 0.2
kick_windup_distance: 0.29
trunk_height: 0.39
trunk_roll: 0.101229096615671
trunk_pitch: -0.136135681655558
trunk_yaw: 0.0558505360638186

foot_rise_windup: 0.1
windup_pitch: 0.4
knee_time: 0.1
ankle_time: 0.1


# Timings
move_trunk_time: 0.56
raise_foot_time: 0.15
move_to_ball_time: 0.19
kick_time: 1
move_back_time: 0.07
lower_foot_time: 0.06
move_trunk_back_time: 0.08

# Decisions
choose_foot_corridor_width: 0.4

### Stabilizer ###
use_center_of_pressure: false
stabilizing_point_x: -0.02
stabilizing_point_y: -0.02

# these values are used only if use_center_of_pressure is true
pid_x/p: 0.2
pid_x/i: 0
pid_x/d: 0
pid_y/p: 0.5
pid_y/i: 0.0015
pid_y/d: 1.5

### Visualization ###
spline_smoothness: 100
