### Engine ###

kick_speed: 6.0

# Distances and positions
engine_rate: 500
foot_rise: 0.09
foot_distance: 0.23
kick_windup_distance: 0.31
trunk_height: 0.4
trunk_roll: -0.0506145483078355
trunk_pitch: -0.446804288510548
trunk_yaw: 0.319395253114962

# Timings
move_trunk_time: 0.41
raise_foot_time: 0.33
move_to_ball_time: 0.35
kick_time: 0.11
move_back_time: 0.17
lower_foot_time: 0.01
move_trunk_back_time: 0.06

# Decisions
choose_foot_corridor_width: 0.4

### Stabilizer ###
use_center_of_pressure: false
stabilizing_point_x: 0.01
stabilizing_point_y: -0.02

# these values are used only if use_center_of_pressure is true
pid_x/p: 0.2
pid_x/i: 0
pid_x/d: 0
pid_y/p: 0.5
pid_y/i: 0.0015
pid_y/d: 1.5

### Visualization ###
spline_smoothness: 100
