dynup:
  # Engine
  engine_rate: 240

  # end pose
  arm_extended_length: 0.3
  foot_distance: 0.193
  hand_walkready_pitch: -25.0
  hand_walkready_height: -0.35
  trunk_height: 0.391
  trunk_pitch: 0.178
  trunk_x_final: -0.0256

  arm_side_offset: 0.142
  #arm_side_offset: 0.154

  # Back
  arms_angle_back: 127.25
  com_shift_1: 0.068
  com_shift_2: 0.012
  foot_angle: 33.21
  hands_behind_back_x: 0.138
  hands_behind_back_z: 0.152
  leg_min_length_back: 0.24
  time_foot_ground_back: 0.224
  time_full_squat_hands: 0.096
  time_full_squat_legs: 0.032
  time_legs_close: 0.0
  trunk_height_back: 0.129
  trunk_overshoot_angle_back: 0.89
  wait_in_squat_back: 0.416


  # Front
  hands_pitch: -77.97
  leg_min_length_front: 0.26
  max_leg_angle: 60.88
  time_foot_close: 0.256
  time_foot_ground_front: 0.064
  time_hands_front: 0.096
  time_hands_rotate: 0.16
  time_hands_side: 0.224
  time_to_squat: 0.384
  time_torso_45: 0.288
  trunk_overshoot_angle_front: -44.89
  trunk_x_front: 0.052
  wait_in_squat_front: 0.128

  # Rise
  rise_time: 0.672

  # Descend
  descend_time: 0.25

  # Stabilier
  stabilizing: False
  minimal_displacement: False
  stable_threshold: 0.05
  stable_duration: 100
  stabilization_timeout: 2

  # Visualizer
  spline_smoothness: 100
  display_debug: True

  pid_trunk_roll:
    p: 0.36
    i: 0.8674
    d: 0.03735
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: True
    publish_state: False
  pid_trunk_pitch:
    p: -0.42
    i: -5.31646
    d: -0.008295
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: True
    publish_state: False
