walking:
  ros__parameters:
    engine:
      double_support_ratio: 0.009928297385744567 
      foot_distance: 0.15711589850479166 
      foot_rise: 0.05981311777666854 
      freq: 2.784877119885708 
      trunk_height: 0.39378348776938393 
      trunk_phase: -0.1645938828588562 
      trunk_pitch: 0.25967971865872946 
      trunk_pitch_p_coef_forward: 0.3202592230988127 
      trunk_pitch_p_coef_turn: -0.4995838392898083 
      trunk_swing: 0.203073881443286 
      trunk_x_offset: 0.0034965763857180854 
      trunk_y_offset: -0.001372884656229225 
      trunk_z_movement: 0.0009167670382079369 
      first_step_swing_factor: 1.0 
      first_step_trunk_phase: -0.5 
      foot_apex_phase: 0.5 
      foot_overshoot_phase: 1.0 
      foot_overshoot_ratio: 0.0 
      foot_put_down_phase: 1.0 
      foot_put_down_z_offset: 0.0 
      foot_z_pause: 0.0 
      trunk_pause: 0.0 
      trunk_x_offset_p_coef_forward: 0.0
      trunk_x_offset_p_coef_turn: 0.0

      kick_length: 0.09
      kick_vel: 0.2
      kick_phase: 0.75

    node:
      # update frequency of the engine
      engine_freq: 500.0

      # parameters for bioIK
      ik_timeout: 0.01
      ik_reset: True

      debug_active: False

      max_step_x: 10000.0
      max_step_y: 10000.0
      max_step_xy: 10000.0
      max_step_z: 100000.0
      max_step_angular: 10000.0

      x_speed_multiplier: 1.1
      y_speed_multiplier: 1.2
      yaw_speed_multiplier: 1.1

      imu_active: False
      imu_pitch_threshold: 0.19
      imu_roll_threshold: 0.4
      imu_pitch_vel_threshold: 1.3
      imu_roll_vel_threshold: 5.7
      pause_duration: 3.0

      pressure_phase_reset_active: False
      ground_min_pressure: 1.5
      phase_reset_phase: 0.25
      joint_min_effort: 35.0
      effort_phase_reset_active: False

walk_pid_trunk_fused_pitch:
  ros__parameters:
    p: 0.0
    i: 0.0
    d: 0.0
    i_clamp: 0.0
    i_clamp_min: 0.0
    i_clamp_max: 0.0
    antiwindup: False

walk_pid_trunk_fused_roll:
  ros__parameters:
    p: 0.0
    i: 0.0
    d: 0.0
    i_clamp: 0.0
    i_clamp_min: 0.0
    i_clamp_max: 0.0
    antiwindup: False
