walking:
  engine:

    double_support_ratio: 0.439596286644122
    first_step_swing_factor: 0.989033428831421
    foot_distance: 0.203124574537751
    foot_rise: 0.100411312094506
    freq: 3.12873643742102
    trunk_height: 0.380974551045401
    trunk_phase: -0.19523826257412
    trunk_pitch: -0.189314552270696
    trunk_pitch_p_coef_forward: -2.62191997733776
    trunk_pitch_p_coef_turn: -1.56524191969166
    trunk_swing: 0.625021037935647
    trunk_x_offset: 0.0073094266122581
    trunk_y_offset: -0.00114613940636394
    trunk_z_movement: 0.00926486218467733
    directions_left: 1.0
    early_termination_at: [-0.6000000000000001, 0, 0.75]
    fall_sum: 1.0
    first_step_trunk_phase: -0.5
    foot_apex_phase: 0.5
    foot_overshoot_phase: 1
    foot_overshoot_ratio: 0.0
    foot_put_down_phase: 1
    foot_z_pause: 0
    pose_obj: 0.24005767665296518
    stability_obj: 0.2886200042430882
    time_obj: 1.311999999996715
    trunk_pause: 0

    kick_length: 0.09
    kick_vel: 0.2
    kick_phase: 0.75

  node:
    # update frequency of the engine
    engine_freq: 33.0

    # parameters for bioIK
    ik_timeout: 0.01

    debug_active: True

    trunkYOnlyInDoubleSupport: False

    max_step_x: 100
    max_step_y: 100
    max_step_xy: 100
    max_step_z: 1000
    max_step_angular: 1000.000

    x_speed_multiplier: 1
    y_speed_multiplier: 1
    yaw_speed_multiplier: 1


    vel: -1
    acc: -1
    pwm: -1

    imu_active: False
    imu_pitch_threshold: 0.19
    imu_roll_threshold: 0.4
    imu_pitch_vel_threshold: 1.3
    imu_roll_vel_threshold: 5.7
    pause_duration: 3.0

    phase_reset_active: False
    ground_min_pressure: 1.5
    phase_reset_phase: 0.25
    joint_min_effort: 35
    effort_phase_reset_active: False


  pid_trunk_pitch:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_trunk_roll:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_trunk_fused_pitch:
    p: 0.0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_trunk_fused_roll:
    p: 0.0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_trunk_gyro_roll:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_trunk_gyro_pitch:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_cop_x:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_cop_y:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_ankle_left_pitch:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_ankle_right_pitch:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_ankle_left_roll:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_ankle_right_roll:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_hip_pitch:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_hip_roll:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_foot_pos_x:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True

  pid_foot_pos_y:
    p: 0
    i: 0
    d: 0
    i_clamp: 0
    i_clamp_min: 0
    i_clamp_max: 0
    antiwindup: False
    publish_state: True